### PR TITLE
Improve Travis post summary by using C-style formatting

### PR DESCRIPTION
**Pull request by mihaigalos**

### CODE REVIEW

**Comment by mihaigalos** [comment]
@chaifeng, seems this is still having problems on Travis..

**Comment by chaifeng** [comment]
Didn't you change the line which checks `TRAVIS_PULL_REQUEST`?

[Improve Travis post summary by using C-style formatting by mihaigalos · Pull Request #19 · mihaigalos/miniboot](https://github.com/mihaigalos/miniboot/pull/19/commits/49040aef8a0ca796845d749f2362aebc7139cf1b#diff-0c528327a92b4f2547397b8810078922R4)

**Comment by chaifeng** [comment]
See [Fix inconsistency in variable type which is bool by mihaigalos · Pull Request #18 · mihaigalos/miniboot](https://github.com/mihaigalos/miniboot/pull/18/files)

**Comment by mihaigalos** [comment]
OK, missed a rebase onto `master` :smile:. Still don't understand the error message..

**Comment by chaifeng** [comment]
> OK, missed a rebase onto `master` 😄. Still don't understand the error message..

I remembered there were 4 types of errors:

1. Using `\` to break lines in YAML: invalid YAML syntax.
2. Didn't check `TRAVIS_PULL_REQUEST`, this may cause invalid API URLs.
3. Forgot to escape double quotes in a string, this causes submitting incomplete JSON data.
4. Errors from Travis CI, such as couldn't fetch PGP public key. Just restart the failed builds.

**Comment by mihaigalos** [comment]
Hum. I diffed against a build which did publish something back to the PR. Seems the "\`"  character does not get escaped by the `print -v`.

**Comment by mihaigalos** [comment]
`CI Auto Message`
---
```bash
miniboot.elf  :
section                     size      addr
.data                          0   8388864
.text                       1966     30720
.stab                       6300         0
.stabstr                    4837         0
.comment                      17         0
.note.gnu.avr.deviceinfo      64         0
```

**Comment by mihaigalos** [comment]
@chaifeng : of course I didn't have to escape "\`" since it has no special meaning in C. Duh. Ok, looks good now. Any other open points? Otherwise I'll merge this PR.

**Comment by mihaigalos** [comment]
`CI Auto Message`
---
```bash
miniboot.elf  :
section                     size      addr
.data                          0   8388864
.text                       1966     30720
.stab                       6300         0
.stabstr                    4837         0
.comment                      17         0
.note.gnu.avr.deviceinfo      64         0
```

**Comment by chaifeng** [comment]
Looks good.

- Yes, need to escape ``` ` ... ` ``` in double-quotes, but not in single-quotes, like `$( ... )`
- Usually, we'd better output error messages to stderr console.
- Don't forget to put variables in double-quotes, unless we know we don't need double-quotes in the case.

**Pull request merged**
